### PR TITLE
Added Modelling Stuff

### PR DESCRIPTION
**Pull request by jacktan1**

### CODE REVIEW

**Comment by Zhang-Haipeng** [comment]
@thejacktan  As suggested by Tiffany, I think it's better to put all the output imgs and tables into `results` folder for report use.   And I'd also suggest adding prefixes like `Modeling-xxx`.  (I've named all EAD outputs like "EDA-xxx").

**Comment by jnederlo** [comment]
@thejacktan Good first go, logical order and easy to read. Couple things to note:

- We need to have the script read in command line arguments like I did in `download_data.py`
- I think we need to have a `main()` function.
- It would be better and helpful if you could structure the code into logical functions.
  - For example, in `main()` we would call a `fit()` function to fit the models, and then a `predict()` function that would fit each model.

Can you start by adding in the command line arguments and then we can merge and see about adding in other functions.

**Comment by jacktan1** [comment]
There's a bug with reading command line arguments. Not sure why. Can you help locate it?
default name for file: player_data_ready.csv
default save folder: img

**Review by jnederlo — APPROVED** [review]
@thejacktan Thanks for adding this stuff! I'll try to find the bug with the CL arguments.

**Pull request merged**
